
--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'C:\Users\Shambhu\Downloads\Star schema sql_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "FACT_CRIME" entity.
CREATE TABLE FACT_CRIME(
	fact_crime_key	INTEGER NOT NULL,
	region_key	INTEGER NOT NULL UNIQUE,
	time_key	INTEGER NOT NULL UNIQUE,
	crime_type_key	INTEGER NOT NULL UNIQUE,
	police_station_key	INTEGER NOT NULL UNIQUE,
	crime_status_key	INTEGER NOT NULL UNIQUE,
	total_crime	INTEGER,
	resolved_crime	INTEGER,
	unresolved_crime	INTEGER,
	escalated_flag	INTEGER,
	crime_severity	INTEGER,
	fk1_region_key	INTEGER NOT NULL,
	fk2_time_key	INTEGER NOT NULL,
	fk3_crime_type_key	INTEGER NOT NULL,
	fk4_police_station_key	INTEGER NOT NULL,
	fk5_crime_status_key	INTEGER NOT NULL,
	-- Specify the PRIMARY KEY constraint for table "FACT_CRIME".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_FACT_CRIME PRIMARY KEY (fact_crime_key)
);

-- Create a Database table to represent the "DIM_LOCATION" entity.
CREATE TABLE DIM_LOCATION(
	region_key	INTEGER NOT NULL,
	region_id	INTEGER,
	region_name	VARCHAR(25),
	area	VARCHAR(20),
	city	VARCHAR(20),
	data_source	VARCHAR(15),
	-- Specify the PRIMARY KEY constraint for table "DIM_LOCATION".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_LOCATION PRIMARY KEY (region_key)
);

-- Create a Database table to represent the "DIM_TIME" entity.
CREATE TABLE DIM_TIME(
	time_key	INTEGER NOT NULL,
	year	INTEGER,
	month	INTEGER,
	day	INTEGER,
	quarter	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "DIM_TIME".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_TIME PRIMARY KEY (time_key)
);

-- Create a Database table to represent the "DIM_CRIME_TYPE" entity.
CREATE TABLE DIM_CRIME_TYPE(
	crime_type_key	INTEGER NOT NULL,
	crime_id	INTEGER,
	crime_type_name	VARCHAR(20),
	crime_category	VARCHAR(15),
	severity_level	VARCHAR(8),
	data_source	VARCHAR(15),
	-- Specify the PRIMARY KEY constraint for table "DIM_CRIME_TYPE".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_CRIME_TYPE PRIMARY KEY (crime_type_key)
);

-- Create a Database table to represent the "DIM_POLICE_STATION" entity.
CREATE TABLE DIM_POLICE_STATION(
	police_station_key	INTEGER NOT NULL,
	station_id	INTEGER,
	station_name	VARCHAR(20),
	data_source	VARCHAR(15),
	-- Specify the PRIMARY KEY constraint for table "DIM_POLICE_STATION".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_POLICE_STATION PRIMARY KEY (police_station_key)
);

-- Create a Database table to represent the "DIM_CRIME_STATUS" entity.
CREATE TABLE DIM_CRIME_STATUS(
	crime_status_key	INTEGER NOT NULL,
	crime_status	VARCHAR(10),
	data_source	VARCHAR(15),
	-- Specify the PRIMARY KEY constraint for table "DIM_CRIME_STATUS".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_DIM_CRIME_STATUS PRIMARY KEY (crime_status_key)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "FACT_CRIME_DIM_LOCATION" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME"
-- correctly references the primary key of table "DIM_LOCATION"

ALTER TABLE FACT_CRIME ADD CONSTRAINT fk1_FACT_CRIME_to_DIM_LOCATION FOREIGN KEY(fk1_region_key) REFERENCES DIM_LOCATION(region_key) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "FACT_CRIME_DIM_TIME" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME"
-- correctly references the primary key of table "DIM_TIME"

ALTER TABLE FACT_CRIME ADD CONSTRAINT fk2_FACT_CRIME_to_DIM_TIME FOREIGN KEY(fk2_time_key) REFERENCES DIM_TIME(time_key) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "FACT_CRIME_DIM_CRIME_TYPE" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME"
-- correctly references the primary key of table "DIM_CRIME_TYPE"

ALTER TABLE FACT_CRIME ADD CONSTRAINT fk3_FACT_CRIME_to_DIM_CRIME_TYPE FOREIGN KEY(fk3_crime_type_key) REFERENCES DIM_CRIME_TYPE(crime_type_key) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "FACT_CRIME_DIM_POLICE_STATION" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME"
-- correctly references the primary key of table "DIM_POLICE_STATION"

ALTER TABLE FACT_CRIME ADD CONSTRAINT fk4_FACT_CRIME_to_DIM_POLICE_STATION FOREIGN KEY(fk4_police_station_key) REFERENCES DIM_POLICE_STATION(police_station_key) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Alter table to add new constraints required to implement the "FACT_CRIME_DIM_CRIME_STATUS" relationship

-- This constraint ensures that the foreign key of table "FACT_CRIME"
-- correctly references the primary key of table "DIM_CRIME_STATUS"

ALTER TABLE FACT_CRIME ADD CONSTRAINT fk5_FACT_CRIME_to_DIM_CRIME_STATUS FOREIGN KEY(fk5_crime_status_key) REFERENCES DIM_CRIME_STATUS(crime_status_key) ON DELETE RESTRICT ON UPDATE RESTRICT;


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
